-- =============================================================================
-- Scene 1 Part C Notebook Content: "The Catch" — Pipeline Review
-- WiD 2026 Demo — "The Future You"
-- =============================================================================
-- This file documents the cell contents for a Snowflake Notebook.
-- Create the notebook manually in Snowsight and paste each cell.
--
-- Story: An AI agent built a churn prediction pipeline overnight.
-- The pipeline has a subtle bug: COUNT(*) instead of COUNT(DISTINCT CUSTOMER_ID).
-- Because one customer has multiple accounts (multiple rows), the count is
-- inflated ~2.5×. The presenter "catches" it during review.
-- =============================================================================

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 1 — Markdown                                        │
-- └──────────────────────────────────────────────────────────┘
-- # Pipeline Review: Churn Prediction Refresh
-- ### AI-Generated Pipeline — Scheduled for Pre-Board Call Execution
-- This pipeline was generated by an AI agent overnight to refresh churn
-- predictions before the quarterly board call. Let's review the output
-- before it goes to production.

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 2 — SQL (the buggy pipeline)                        │
-- └──────────────────────────────────────────────────────────┘

-- AI-generated churn prediction refresh
-- Generated by: AI Pipeline Agent v2.1
-- Scheduled: Pre-board call refresh
SELECT COUNT(*) AS at_risk_customers
FROM RETAILBANK_2028.PUBLIC.CUSTOMERS
WHERE CHURN_RISK_SCORE > 0.6;
-- Expected: should show customers at risk for board presentation

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 3 — Markdown                                        │
-- └──────────────────────────────────────────────────────────┘
-- ## ⚠️ Result: ~813 at-risk customers
-- **Last quarter: ~330 at-risk customers**
--
-- That's a **150% increase** in one quarter. Does that make business sense?
--
-- Let's investigate the data...

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 4 — SQL (investigation)                             │
-- └──────────────────────────────────────────────────────────┘

-- How many rows vs unique customers do we have?
SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT CUSTOMER_ID) AS unique_customers,
    COUNT(DISTINCT ACCOUNT_ID) AS unique_accounts
FROM RETAILBANK_2028.PUBLIC.CUSTOMERS;
-- One customer can have MULTIPLE accounts → multiple rows per customer
-- COUNT(*) counts rows, not distinct customers!

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 5 — SQL (the fix)                                   │
-- └──────────────────────────────────────────────────────────┘

-- FIXED: Count distinct customers, not rows
SELECT COUNT(DISTINCT CUSTOMER_ID) AS at_risk_customers
FROM RETAILBANK_2028.PUBLIC.CUSTOMERS
WHERE CHURN_RISK_SCORE > 0.6;
-- Result: ~325 at-risk customers — in line with last quarter's trend

-- ┌──────────────────────────────────────────────────────────┐
-- │ CELL 6 — Markdown                                        │
-- └──────────────────────────────────────────────────────────┘
-- ## ✅ Fixed: ~325 at-risk customers
-- Back in line with the quarterly trend.
--
-- ### What happened?
-- The AI used `COUNT(*)` instead of `COUNT(DISTINCT CUSTOMER_ID)`.
-- Both run without error. But because one customer can have multiple
-- accounts, there are **1,966 rows** for only **800 unique customers**.
-- `COUNT(*)` counted every account row as a separate customer,
-- inflating the result by ~2.5×.
--
-- ### The lesson
-- The AI wrote the query correctly in every other way. But it had no
-- business context. It didn't know that one customer can have multiple
-- accounts. **That knowledge lives in your head, not in the data.**
--
-- > Technical judgment is the skill. Knowing when the answer is wrong
-- > — even before you know why.
